package org.cleancoders.infrastructure.persistence.testdata;

import org.cleancoders.infrastructure.persistence.InMemoryReservationRepo;
import org.cleancoders.reservation.domain.Reservation;
import org.cleancoders.reservation.domain.ReservationStatus;

import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * {@link InMemoryReservationRepo} pre-seeded with test reservations.
 * <p>
 * Uses the same user IDs as {@link TestDataUserRepo}.
 */
public class TestDataReservationRepo extends InMemoryReservationRepo {

    /** User IDs — must match those generated by {@link TestDataUserRepo}. */
    public static final String ZHANGSAN = "user-zhangsan";
    public static final String LISI = "user-lisi";
    public static final String WANGWU = "user-wangwu";
    public static final String ZHAOLIU = "user-zhaoliu";
    public static final String ADMIN = "user-admin";

    public TestDataReservationRepo() {
        LocalDate today = LocalDate.now();

        // --- RESERVED ---
        save(new Reservation("res-1", ZHANGSAN, "room-1", 1, "ts-2", today));
        save(new Reservation("res-2", LISI, "room-1", 3, "ts-2", today));
        save(new Reservation("res-3", WANGWU, "room-1", 5, "ts-3", today));

        // --- CHECKED_IN ---
        Reservation r4 = new Reservation("res-4", ZHANGSAN, "room-1", 2, "ts-1", today);
        save(r4);
        r4.checkIn();

        Reservation r5 = new Reservation("res-5", ZHAOLIU, "room-1", 4, "ts-1", today);
        save(r5);
        r5.checkIn();

        // --- CANCELLED ---
        Reservation r6 = new Reservation("res-6", LISI, "room-2", 1, "ts-3", today.minusDays(1));
        save(r6);
        r6.cancel();

        // --- CHECKED_OUT ---
        Reservation r7 = new Reservation("res-7", WANGWU, "room-2", 2, "ts-1", today.minusDays(1));
        save(r7);
        r7.checkIn();
        r7.checkOut();

        // --- EXPIRED ---
        Reservation r8 = new Reservation("res-8", ZHAOLIU, "room-1", 6, "ts-2", today.minusDays(2));
        save(r8);
        r8.expire();
    }
}
